name: model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py

          cat log.txt >> report.md
          cml-publish logistic_regression.png --md >> report.md
          cml-publish Random_Forest_classifier.png --md >> report.md
          cml-send-comment report.md
